version: "3.8"

services:
  flask:
    build:
      context: ./flask # Path to the flask folder
    container_name: flask-backend
    ports:
      - "5000:5000" # Map port 5000 of the container to 5000 of the host machine
    networks:
      - mynetwork
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development # Optional: Set Flask environment to development

  next:
    build:
      context: ./next-app # Path to the next-app folder
    container_name: next-frontend
    ports:
      - "3000:3000" # Map port 3000 of the container to 3000 of the host machine
    networks:
      - mynetwork
    depends_on:
      - flask # Ensure that the Flask container is ready before starting the Next.js container
    environment:
      - NEXT_PUBLIC_API_URL=http://flask:5000 # If the frontend needs to talk to the Flask API

networks:
  mynetwork:
    driver: bridge
